### ISSUE TITLE
How to ask for scope in the request, scope must be presented on the initial request.

### ISSUE THREAD

**Issue by tomandersen** [IBM-Swift/Kitura-CredentialsGoogle#20]
The scope is hardwired to profile. This means that the dialog that comes from google tells the user that the calling application does not want the users email (for instance). 

In other words line 149 has 
try response.redirect("https://accounts.google.com/o/oauth2/auth?client_id=\(clientId)&redirect_uri=\(callbackUrl)&scope=profile&response_type=code")

the scope hard wired. 

This needs to be settable from the app calling for authentication.

Further if we change line 149 to include the email scope, and add the returned email address from google to the UserProfile on line 120, the Kitura-Credentials  above this will remove the email.

The rebuild of the UserProfile happens on lines 70 - 74 in 
https://github.com/IBM-Swift/Kitura-Credentials/blob/master/Sources/Credentials/Credentials.swift

Since the Kitura-Credentials rebuilds the profile, it seems like that is a bug, but I'm not sure on that.

**Comment by irar2** [comment]
Yes, the scope is hard wired and we only keep the user id and name.
I will try to make both the scope and user profile configurable.

**Comment by irar2** [comment]
I created an issue in Kitura for this problem - IBM-Swift/Kitura#888

**Comment by irar2** [comment]
@tomandersen This should be fixed now, could you please verify?

**Comment by tomandersen** [comment]
Sorry - can't verify with a code test right now, as we are not actively using Kitura swift, but the code looks like it should do the trick. Thanks.
